### PR TITLE
Fix deprication warning being reported on import

### PR DESCRIPTION
**Pull request by jzyworonek**
## Overview

`DeprecationWarning` was being reported on import.

```
ImportError while loading conftest '/app/tests/conftest.py'.
tests/conftest.py:11: in <module>
    from src.core.fastapi import get_application, get_router
src/core/fastapi.py:9: in <module>
    from msgraph import GraphServiceClient
/usr/local/lib/python3.12/site-packages/msgraph/__init__.py:5: in <module>
    from .graph_request_adapter import GraphRequestAdapter
/usr/local/lib/python3.12/site-packages/msgraph/graph_request_adapter.py:3: in <module>
    from kiota_abstractions.authentication import AuthenticationProvider
/usr/local/lib/python3.12/site-packages/kiota_abstractions/authentication/__init__.py:3: in <module>
    from .anonymous_authentication_provider import AnonymousAuthenticationProvider
/usr/local/lib/python3.12/site-packages/kiota_abstractions/authentication/anonymous_authentication_provider.py:9: in <module>
    from ..request_information import RequestInformation
/usr/local/lib/python3.12/site-packages/kiota_abstractions/request_information.py:20: in <module>
    from .base_request_configuration import RequestConfiguration
/usr/local/lib/python3.12/site-packages/kiota_abstractions/base_request_configuration.py:30: in <module>
    class BaseRequestConfiguration(RequestConfiguration):
/usr/local/lib/python3.12/site-packages/kiota_abstractions/base_request_configuration.py:31: in BaseRequestConfiguration
    warn(
E   DeprecationWarning: BaseRequestConfiguration is deprecated. Use RequestConfiguration class instead.
```

## Related Issue

Fixes # (issue)

### Demo

Simplest reproduction

```
python -Wd -c "from kiota_abstractions.base_request_configuration import RequestConfiguration"
/Users/jacobzyworonek/Repo/kiota-abstractions-python/kiota_abstractions/base_request_configuration.py:31: DeprecationWarning: BaseRequestConfiguration is deprecated. Use RequestConfiguration class instead.
  warn(
```

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

**Comment by jzyworonek** [comment]
@microsoft-github-policy-service agree

**Review by andrueastman — COMMENTED** [review]
Thanks for the contribution @jzyworonek 

Any chance you can
- look into the linting/formatting error at https://github.com/microsoft/kiota-abstractions-python/actions/runs/8408794432/job/23042076004?pr=250
- Update the changelog.md file at the root repository as well as bump the [minor version](https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/_version.py) as well
-

**Comment by andrueastman** [comment]
> Update the changelog.md file at the root repository as well as bump the [minor version](https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/_version.py) as well

Apologies @jzyworonek . I should have said patch version here. Otherwise looks good to me.

cc @samwelkanda for final review and merge/release.

**Comment by baywet** [comment]
@andrueastman Since Samwel has been re-affected, I don't think we should expect much from him moving forward. Please go ahead with merge/release.

**Review by andrueastman — APPROVED** [review]

**Pull request merged**
